package net.chirripo.entities;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import net.chirripo.entities.Routes;
import net.chirripo.entities.WayPoints;

import net.chirripo.entities.RoutesDao;
import net.chirripo.entities.WayPointsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig routesDaoConfig;
    private final DaoConfig wayPointsDaoConfig;

    private final RoutesDao routesDao;
    private final WayPointsDao wayPointsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        routesDaoConfig = daoConfigMap.get(RoutesDao.class).clone();
        routesDaoConfig.initIdentityScope(type);

        wayPointsDaoConfig = daoConfigMap.get(WayPointsDao.class).clone();
        wayPointsDaoConfig.initIdentityScope(type);

        routesDao = new RoutesDao(routesDaoConfig, this);
        wayPointsDao = new WayPointsDao(wayPointsDaoConfig, this);

        registerDao(Routes.class, routesDao);
        registerDao(WayPoints.class, wayPointsDao);
    }
    
    public void clear() {
        routesDaoConfig.getIdentityScope().clear();
        wayPointsDaoConfig.getIdentityScope().clear();
    }

    public RoutesDao getRoutesDao() {
        return routesDao;
    }

    public WayPointsDao getWayPointsDao() {
        return wayPointsDao;
    }

}
