package net.chirripo.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WAY_POINTS.
 */
public class WayPoints {

    private Long id;
    private int count;
    private double lat;
    private double lng;
    private long routeId;

    public WayPoints() {
    }

    public WayPoints(Long id) {
        this.id = id;
    }

    public WayPoints(Long id, int count, double lat, double lng, long routeId) {
        this.id = id;
        this.count = count;
        this.lat = lat;
        this.lng = lng;
        this.routeId = routeId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    public double getLat() {
        return lat;
    }

    public void setLat(double lat) {
        this.lat = lat;
    }

    public double getLng() {
        return lng;
    }

    public void setLng(double lng) {
        this.lng = lng;
    }

    public long getRouteId() {
        return routeId;
    }

    public void setRouteId(long routeId) {
        this.routeId = routeId;
    }

}
