package net.chirripo.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WAY_POINTS.
 */
public class WayPoints {

    private Long id;
    private double lat;
    private double lng;
    private double distance;
    private long routeId;
    private long count;

    public WayPoints() {
    }

    public WayPoints(Long id) {
        this.id = id;
    }

    public WayPoints(Long id, double lat, double lng, double distance, long routeId, long count) {
        this.id = id;
        this.lat = lat;
        this.lng = lng;
        this.distance = distance;
        this.routeId = routeId;
        this.count = count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getLat() {
        return lat;
    }

    public void setLat(double lat) {
        this.lat = lat;
    }

    public double getLng() {
        return lng;
    }

    public void setLng(double lng) {
        this.lng = lng;
    }

    public double getDistance() {
        return distance;
    }

    public void setDistance(double distance) {
        this.distance = distance;
    }

    public long getRouteId() {
        return routeId;
    }

    public void setRouteId(long routeId) {
        this.routeId = routeId;
    }

    public long getCount() {
        return count;
    }

    public void setCount(long count) {
        this.count = count;
    }

}
